### ISSUE TITLE
the addition of hydrogens at pH 7 from the generated-superposed mol2

### ISSUE THREAD

**Issue by rilaklin** [ambrishroy/LIGSIFT#2]
Hi Ambrish, 
I found that the hydrogen will be automatically assigned to, for example,  phosphate group, without considering its pKa ( while the input has correct assignment of the hydrogens). Is it possible to add this condition in generation of the output? thank you.

**Comment by ambrishroy** [comment]
Added an Option -r to control addition of Hydrogen
